name: Deploy
run-name: ${{ gitea.actor }} is deploying ${{ gitea.repository }}
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: docker.gitea.com/runner-images:ubuntu-latest
      volumes:
        - /opt/hugo/toledot.post-self.ink:/opt/hugo/toledot.post-self.ink
    env:
      DART_SASS_VERSION: 1.98.0
    steps:
      - name: Check out repo
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.157.0'
          extended: true

      - name: Install Dart Sass
        run: |
          curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz \
          && tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz \
          && cp -r dart-sass/* /usr/local/bin \
          && rm -rf dart-sass* \
          && sass --embedded --version

      - name: Build site
        run: |
          hugo build --gc --minify --baseURL https://toledot.post-self.ink --destination /opt/hugo/toledot.post-self.ink

      - name: Set permissions
        run: chown -R www-data:www-data /opt/hugo/toledot.post-self.ink
